services:
  user-service:
    build:
      context: ./backend/user_service
    ports:
      - "8000:8000"

  classification-service:
    build:
      context: ./backend/classification_service
    ports:
      - "8001:8001"
    volumes:
      - photo_storage:/app/storage

volumes:
  photo_storage:
    driver: local
